# Generated by Django 3.2.7 on 2021-10-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='reverse',
            field=models.BooleanField(default=False),
        ),
    ]
