# Generated by Django 3.2.7 on 2021-11-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_reverse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
    ]
