# Generated by Django 3.2.7 on 2021-11-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_video_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='motion_direction',
            field=models.IntegerField(default=90),
        ),
    ]
