# Generated by Django 3.2.7 on 2021-11-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_video_motion_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='black_and_white',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='blue',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='video',
            name='brightness',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='video',
            name='contrast',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='video',
            name='datamosh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='fade',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='green',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='video',
            name='hue',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='video',
            name='mirror',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='motion_intensity',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='video',
            name='paintify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='red',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='video',
            name='repeated_segments',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='video',
            name='repeated_songs',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='video',
            name='rotate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='saturation',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='video',
            name='scroll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='video_shift',
            field=models.IntegerField(default=0),
        ),
    ]
